import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import localFont from 'next/font/local';
import './globals.css';

// 1. Configure the local font
const openRunde = localFont({
  src: [
    {
      path: './fonts/OpenRunde-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/OpenRunde-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/OpenRunde-Bold.woff2',
      weight: '700',
      style: 'normal',
    }
  ],
  // 2. Define a CSS variable to use in Tailwind
  variable: '--font-open-runde',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // 3. Inject the variable into the HTML tag
    <html lang="en" className={`${openRunde.variable}`}>
      {/* 4. Apply the Tailwind font-sans class to the body */}
      <body className="font-sans bg-slate-50 text-slate-800 antialiased">
        {children}
      </body>
    </html>
  );
}
